import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Rasmus',
      email: 'admin@admin.com',
      password: bcrypt.hashSync('123', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Rasmus',
        logo: '/images/logo1.jpg',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Carl',
      email: 'user@user.com',
      password: bcrypt.hashSync('123', 8),
      isAdmin: false,
    },
    {
      name: 'Filip',
      email: 'seller@seller.com',
      password: bcrypt.hashSync('123', 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'Filip',
        logo: '/images/logo2.jpg',
        description: 'seller',
        rating: 3,
        numReviews: 40,
      },
    },
  ],
  products: [
    {
      name: 'Cheap Headphones',
      category: 'Red',
      image: 'https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/19.jpg',
      price: 5,
      countInStock: 13,
      brand: 'Samsung',
      rating: 2.5,
      numReviews: 11,
      description: 'high quality',
    },
    {
      name: 'Ruby-3021',
      category: 'Red',
      image: 'https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/17.jpg',
      price: 145,
      countInStock: 17,
      brand: 'Apple',
      rating: 4.0,
      numReviews: 24,
      description: 'high quality',
    },
    {
      name: 'Simple Blue',
      category: 'Blue',
      image: 'https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/18.jpg',
      price: 77,
      countInStock: 0,
      brand: 'Apple',
      rating: 2.0,
      numReviews: 17,
      description: 'high quality',
    },
    {
      name: 'Red Headphones',
      category: 'Red',
      image: 'https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/19.jpg',
      price: 18,
      countInStock: 8,
      brand: 'Samsung',
      rating: 2.5,
      numReviews: 2,
      description: 'high quality',
    },
    {
      name: 'Not Airpods',
      category: 'Red',
      image: 'https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/17.jpg',
      price: 65,
      countInStock: 3,
      brand: 'Samsung',
      rating: 1.5,
      numReviews: 19,
      description: 'decent quality',
    },
    {
      name: 'Sapphire-1337',
      category: 'Blue',
      image: 'https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/18.jpg',
      price: 139,
      countInStock: 20,
      brand: 'Apple',
      rating: 5.0,
      numReviews: 125,
      description: 'high quality',
    },
  ],
}
export default data